/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;



/**
 *
 * @author Andrew Dong
 */
public class DrawingScreenFrame extends javax.swing.JFrame {
    
    
    /**
     * Creates new form DrawingScreen
     */
    public DrawingScreenFrame() {
        // Intializing the intial drawing application
        // this is handle by netBeans design feature. DO NOT
        // touch any code in the initComponents method!!!
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * This will contain all the initialize element of our canvas
     * @Author: Group 34
     * DATE LAST MODIFIED: 02/07/2016
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        redButton = new javax.swing.JButton();
        blueButton = new javax.swing.JButton();
        greenButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CPSC441 - GROUP 34 - Collaborative Drawing");

        redButton.setText("RED");

        blueButton.setText("BLUE");

        greenButton.setText("GREEN");

        clearButton.setText("CLEAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(redButton)
                .addGap(26, 26, 26)
                .addComponent(blueButton)
                .addGap(18, 18, 18)
                .addComponent(greenButton)
                .addGap(28, 28, 28)
                .addComponent(clearButton)
                .addContainerGap(516, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(redButton)
                    .addComponent(blueButton)
                    .addComponent(greenButton)
                    .addComponent(clearButton))
                .addContainerGap(440, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton blueButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton greenButton;
    private javax.swing.JButton redButton;
    // End of variables declaration//GEN-END:variables


}
