package GUI;

import java.awt.BorderLayout;
import java.awt.Container;
import java.awt.EventQueue;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.InetAddress;
import java.net.UnknownHostException;

import javax.swing.*;
import javax.swing.border.EmptyBorder;

import Network.*;

import javax.swing.GroupLayout.Alignment;
import java.awt.Font;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 * This Class will generate the create canvas page for the user. GUI was design in windows builder and 
 * the initialization code is generated by windows builder
 * @author Group 34
 * Last Modified: March 24th 2016
 *
 */
public class CreatingCanvas extends JFrame implements ActionListener
{

	private JPanel contentPane;
	private JButton btnCreateNewCanvas;
	private JButton btnJoinExistingCanvas;
	private CanvasClient client;

	private int srcPort = 9000;
	private int dstPort = 8000;
	private String stringIP = "";
	private JTextField addFriendTextField;
	private JButton btnListFriends;
	private JList list;
	private JButton btnAddFriend;
	private JLabel lblAddFriend;
	private DefaultListModel model = new DefaultListModel();

	/**
	 * Create the frame.
	 */
	public CreatingCanvas(CanvasClient c) {
		
		client = c;
		initialiaze();

	}

	/**
	 * This will initialize the CreatingCanvas Screen
	 * Generated from the Windows Builder pluggin
	 */
	private void initialiaze() 
	{
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setBounds(100, 100, 556, 538);
		contentPane = new JPanel();
		contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));
		setContentPane(contentPane);
		
		btnCreateNewCanvas = new JButton("Create New Canvas");
		btnCreateNewCanvas.addActionListener(this);
		 
		btnJoinExistingCanvas = new JButton("Join Existing Canvas");
		btnJoinExistingCanvas.addActionListener(this);
		
		lblAddFriend = new JLabel("ADD FRIEND:");
		lblAddFriend.setFont(new Font("Tahoma", Font.BOLD, 9));
		
		addFriendTextField = new JTextField();
		addFriendTextField.setColumns(10);
		
		btnAddFriend = new JButton("Add Friend ");
		btnAddFriend.addActionListener(this);
		
		btnListFriends = new JButton("List Friends");
		btnListFriends.addActionListener(this);
		
		list = new JList(model);
		
		GroupLayout gl_contentPane = new GroupLayout(contentPane);
		gl_contentPane.setHorizontalGroup(
			gl_contentPane.createParallelGroup(Alignment.TRAILING)
				.addGroup(gl_contentPane.createSequentialGroup()
					.addContainerGap()
					.addGroup(gl_contentPane.createParallelGroup(Alignment.TRAILING)
						.addComponent(btnListFriends, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
						.addComponent(btnJoinExistingCanvas, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
						.addComponent(btnCreateNewCanvas, GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
					.addGap(26)
					.addGroup(gl_contentPane.createParallelGroup(Alignment.LEADING, false)
						.addComponent(list, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(lblAddFriend)
						.addGroup(gl_contentPane.createSequentialGroup()
							.addComponent(addFriendTextField, GroupLayout.PREFERRED_SIZE, 191, GroupLayout.PREFERRED_SIZE)
							.addPreferredGap(ComponentPlacement.UNRELATED)
							.addComponent(btnAddFriend)))
					.addGap(26))
		);
		gl_contentPane.setVerticalGroup(
			gl_contentPane.createParallelGroup(Alignment.LEADING)
				.addGroup(gl_contentPane.createSequentialGroup()
					.addGap(34)
					.addGroup(gl_contentPane.createParallelGroup(Alignment.LEADING)
						.addGroup(gl_contentPane.createSequentialGroup()
							.addComponent(btnCreateNewCanvas, GroupLayout.PREFERRED_SIZE, 61, GroupLayout.PREFERRED_SIZE)
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(btnJoinExistingCanvas, GroupLayout.PREFERRED_SIZE, 61, GroupLayout.PREFERRED_SIZE))
						.addGroup(gl_contentPane.createSequentialGroup()
							.addComponent(lblAddFriend)
							.addPreferredGap(ComponentPlacement.RELATED)
							.addGroup(gl_contentPane.createParallelGroup(Alignment.BASELINE)
								.addComponent(addFriendTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(btnAddFriend))))
					.addPreferredGap(ComponentPlacement.UNRELATED)
					.addGroup(gl_contentPane.createParallelGroup(Alignment.LEADING)
						.addGroup(gl_contentPane.createSequentialGroup()
							.addComponent(btnListFriends, GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
							.addGap(255))
						.addGroup(gl_contentPane.createSequentialGroup()
							.addComponent(list, GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
							.addContainerGap())))
		);
		contentPane.setLayout(gl_contentPane);
		
	}


	/**
	 * Will handle all the Action Listener of the button
	 */
	@Override()
	public void actionPerformed(ActionEvent e)
	{
		if(e.getSource() == btnCreateNewCanvas)
		{
			this.dispose();
			try
			{
				this.client.createCanvasRequest();
			}
			catch(Exception ex)
			{
				//IGNORE
			}
		}
		else if(e.getSource() == btnJoinExistingCanvas)
		{
			this.dispose();
			SelectCanvasServer toJoinCanvas = new SelectCanvasServer(client);
			toJoinCanvas.setVisible(true);
		}
		else if(e.getSource() == btnListFriends)
		{
			try{
				client.listFriendMain();
			}
			catch(Exception ex)
			{
				//ignore
			}
		}
		
	}

	//Populate the friends list array with string from server
	public void listFriends(String list)
	{
		System.out.println(list);
		String[] friendsList = list.split("\t");
		for (String friend:friendsList)
			model.addElement(friend);
	}
}
