package GUI;


import Network.CanvasClient;

import java.awt.*;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 * This Class will generate the create account page for the user. GUI was design in windows builder and 
 * the initialization code is generated by windows builder
 * @author Group 34
 * Last Modified: March 24th 2016
 *
 */
public class CreateAccountFrame extends JFrame implements ActionListener 
{
	// Initializing the variables 
	private JPanel contentPane;
	private JTextField usernameField;
	private JTextField passwordField;
	private JTextField passwordFieldConfirm;
	private JButton btnRegister;
	private JButton btnBack;
	private CanvasClient client;
	private ApplicationMainScreen mainFrame;
	private JLabel lblPasswordToRegister;

	/**
	 * Create the frame.
	 * @param frame 
	 */
	public CreateAccountFrame(CanvasClient c, ApplicationMainScreen frame) {
		
		initialize();
		client = c;
		mainFrame = frame;
	
	}
	
	/**
	 * This method will initialize all the components for the create account page
	 */
	public void initialize()
	{
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setBounds(100, 100, 626, 677);
		contentPane = new JPanel();
		contentPane.setBackground(Color.WHITE);
		contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));
		setContentPane(contentPane);
		
		JLabel lblUsername = new JLabel("Username:");
		lblUsername.setFont(new Font("Letter Gothic Std", Font.PLAIN, 22));
		
		usernameField = new JTextField();
		usernameField.setFont(new Font("Letter Gothic Std", Font.PLAIN, 22));
		usernameField.setColumns(10);
		
		JLabel lblPassword = new JLabel("Password:");
		lblPassword.setFont(new Font("Letter Gothic Std", Font.PLAIN, 22));
		
		passwordField = new JTextField();
		passwordField.setFont(new Font("Letter Gothic Std", Font.PLAIN, 22));
		passwordField.setColumns(10);
		
		JLabel lblConfirmPassword = new JLabel("Confirm Password:");
		lblConfirmPassword.setFont(new Font("Letter Gothic Std", Font.PLAIN, 22));
		
		passwordFieldConfirm = new JTextField();
		passwordFieldConfirm.setFont(new Font("Letter Gothic Std", Font.PLAIN, 22));
		passwordFieldConfirm.setColumns(10);
		
		JLabel lblPleaseEnterA = new JLabel("Please enter a username and a ");
		lblPleaseEnterA.setFont(new Font("Letter Gothic Std", Font.BOLD, 22));
		
		btnRegister = new JButton("Sign Up");
		btnRegister.setBackground(Color.DARK_GRAY);
		btnRegister.setForeground(Color.WHITE);
		btnRegister.setFont(new Font("Letter Gothic Std", Font.PLAIN, 27));
		btnRegister.addActionListener(this);
		
		btnBack = new JButton("Back");
		btnBack.setForeground(Color.WHITE);
		btnBack.setFont(new Font("Letter Gothic Std", Font.PLAIN, 27));
		btnBack.setBackground(Color.DARK_GRAY);
		btnBack.addActionListener(this);
		
		lblPasswordToRegister = new JLabel("password to register for an account.");
		lblPasswordToRegister.setFont(new Font("Letter Gothic Std", Font.BOLD, 22));
		
		
		GroupLayout gl_contentPane = new GroupLayout(contentPane);
		gl_contentPane.setHorizontalGroup(
			gl_contentPane.createParallelGroup(Alignment.LEADING)
				.addGroup(gl_contentPane.createSequentialGroup()
					.addGroup(gl_contentPane.createParallelGroup(Alignment.LEADING)
						.addGroup(gl_contentPane.createSequentialGroup()
							.addGap(124)
							.addGroup(gl_contentPane.createParallelGroup(Alignment.LEADING, false)
								.addGroup(Alignment.TRAILING, gl_contentPane.createSequentialGroup()
									.addComponent(btnRegister, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
									.addPreferredGap(ComponentPlacement.RELATED))
								.addComponent(btnBack, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)))
						.addGroup(gl_contentPane.createSequentialGroup()
							.addGap(67)
							.addComponent(lblPasswordToRegister))
						.addGroup(gl_contentPane.createSequentialGroup()
							.addGap(98)
							.addComponent(lblPleaseEnterA))
						.addGroup(gl_contentPane.createSequentialGroup()
							.addGroup(gl_contentPane.createParallelGroup(Alignment.LEADING)
								.addGroup(gl_contentPane.createSequentialGroup()
									.addContainerGap()
									.addComponent(lblConfirmPassword)
									.addGap(2))
								.addGroup(Alignment.TRAILING, gl_contentPane.createSequentialGroup()
									.addContainerGap()
									.addGroup(gl_contentPane.createParallelGroup(Alignment.LEADING)
										.addComponent(lblUsername)
										.addComponent(lblPassword))
									.addPreferredGap(ComponentPlacement.RELATED)))
							.addGroup(gl_contentPane.createParallelGroup(Alignment.LEADING)
								.addComponent(passwordField, GroupLayout.PREFERRED_SIZE, 268, GroupLayout.PREFERRED_SIZE)
								.addComponent(passwordFieldConfirm, GroupLayout.PREFERRED_SIZE, 268, GroupLayout.PREFERRED_SIZE)
								.addComponent(usernameField, GroupLayout.PREFERRED_SIZE, 268, GroupLayout.PREFERRED_SIZE))
							.addGap(67)))
					.addContainerGap())
		);
		gl_contentPane.setVerticalGroup(
			gl_contentPane.createParallelGroup(Alignment.LEADING)
				.addGroup(gl_contentPane.createSequentialGroup()
					.addGap(95)
					.addComponent(lblPleaseEnterA)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(lblPasswordToRegister)
					.addGap(79)
					.addGroup(gl_contentPane.createParallelGroup(Alignment.BASELINE)
						.addComponent(lblUsername)
						.addComponent(usernameField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
					.addPreferredGap(ComponentPlacement.UNRELATED)
					.addGroup(gl_contentPane.createParallelGroup(Alignment.BASELINE)
						.addComponent(lblPassword)
						.addComponent(passwordField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
					.addPreferredGap(ComponentPlacement.UNRELATED)
					.addGroup(gl_contentPane.createParallelGroup(Alignment.BASELINE)
						.addComponent(lblConfirmPassword)
						.addComponent(passwordFieldConfirm, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
					.addGap(41)
					.addComponent(btnRegister, GroupLayout.PREFERRED_SIZE, 52, GroupLayout.PREFERRED_SIZE)
					.addGap(6)
					.addComponent(btnBack, GroupLayout.PREFERRED_SIZE, 52, GroupLayout.PREFERRED_SIZE)
					.addContainerGap())
		);
		contentPane.setLayout(gl_contentPane);
		
	}

	@Override
	/**
	 * Method will handle all the Action Listener of the buttons and text field.
	 */
	public void actionPerformed(ActionEvent e) {
		// TODO Auto-generated method stub
		if(e.getSource() == btnRegister)
		{
			System.out.println("Register Successful");
			//Logic for the register account will be done here
			//Logic methods will be implemented later on in the project

			//Grab the passwords
			String password = passwordField.getText();
			String confirmPassword = passwordFieldConfirm.getText();
			String username = usernameField.getText();
			//Check if the password is same
			if(password.equals(confirmPassword))
			{
				try
				{
					client.createAccount(username, password);
				}
				catch(IOException f)
				{
					//ignore
				}
			}
			// Closes current frame, bring the user back to the main screen
			//this.dispose();
		}
		else if(e.getSource() == btnBack)
		{
			System.out.println("Bring user back to the main screen");
			this.dispose();
			mainFrame.setVisible(true);
		}
	}

	public void createError()
	{
		JFrame diaFrame = new JFrame();
		JOptionPane.showMessageDialog(diaFrame,
				"Username is taken.",
				"Error",
				JOptionPane.WARNING_MESSAGE);
	}

	public void successMessage()
	{
		JFrame diaFrame = new JFrame();
		JOptionPane.showMessageDialog(diaFrame,
				"Account created succesfully.",
				"Success",
				JOptionPane.WARNING_MESSAGE);
	}

}
