package GUI;

import java.awt.BorderLayout;
import java.awt.EventQueue;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;

/**
 * This Class will generate the drawing screen frame  for the user. GUI was design in windows builder and 
 * the initialization code is generated by windows builder
 * @author Group 34
 * Last Modified: March 24th 2016
 *
 */
public class DrawingScreenFrame extends JFrame {

	private JPanel contentPane;


	/**
	 * Create the frame.
	 * @param dstPort 
	 * @param srcPort 
	 * @param stringIP 
	 */
	public DrawingScreenFrame() {
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setBounds(100, 100, 1500,768);
		contentPane = new JPanel();
		contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));
		contentPane.setLayout(new BorderLayout(0, 0));
		setContentPane(contentPane);
	}

}
