package GUI;




import javax.swing.*;
import javax.swing.border.EmptyBorder;

import Network.CanvasClient;

import javax.swing.GroupLayout.Alignment;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.LayoutStyle.ComponentPlacement;


/**
 * This Class will generate the loggin account page for the user. GUI was design in windows builder and 
 * the initialization code is generated by windows builder
 * @author Group 34
 * Last Modified: March 24th 2016
 *
 */
public class LoginScreenFrame extends JFrame implements ActionListener{

	private JPanel contentPane;
	private JTextField usernameField;
	private JTextField passwordField;
	private JButton btnLogin;
	private JButton btnBack;
	private CanvasClient client;
	private ApplicationMainScreen mainScreen;
	private JLabel lblLoginToYour;


	/**
	 * Create the frame.
	 * @param frame 
	 */
	public LoginScreenFrame(CanvasClient c, ApplicationMainScreen frame) {
		initialize();
		client = c;
		mainScreen = frame;
	}
	
	/**
	 * Will initialize the loggin account page
	 */
	public void initialize()
	{
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setBounds(100, 100, 507, 519);
		contentPane = new JPanel();
		contentPane.setBackground(Color.WHITE);
		contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));
		setContentPane(contentPane);
		
		btnLogin = new JButton("Login");
		btnLogin.setBackground(Color.DARK_GRAY);
		btnLogin.setForeground(Color.WHITE);
		btnLogin.setFont(new Font("Letter Gothic Std", Font.PLAIN, 27));
		btnLogin.addActionListener(this);
		
		JLabel usernameLabel = new JLabel("Username:");
		usernameLabel.setFont(new Font("Letter Gothic Std", Font.BOLD, 20));
		
		JLabel lblPassword = new JLabel("Password:");
		lblPassword.setFont(new Font("Letter Gothic Std", Font.BOLD, 20));
		
		usernameField = new JTextField();
		usernameField.setFont(new Font("Letter Gothic Std", Font.PLAIN, 20));
		usernameField.setColumns(10);
		
		passwordField = new JTextField();
		passwordField.setFont(new Font("Letter Gothic Std", Font.PLAIN, 22));
		passwordField.setColumns(10);
		
		btnBack = new JButton("Back");
		btnBack.setBackground(Color.DARK_GRAY);
		btnBack.setForeground(Color.WHITE);
		btnBack.setFont(new Font("Letter Gothic Std", Font.PLAIN, 27));
		btnBack.addActionListener(this);
		
		lblLoginToYour = new JLabel("Login to your account");
		lblLoginToYour.setFont(new Font("Letter Gothic Std", Font.BOLD, 27));
		
		GroupLayout gl_contentPane = new GroupLayout(contentPane);
		gl_contentPane.setHorizontalGroup(
			gl_contentPane.createParallelGroup(Alignment.LEADING)
				.addGroup(Alignment.TRAILING, gl_contentPane.createSequentialGroup()
					.addContainerGap(58, Short.MAX_VALUE)
					.addGroup(gl_contentPane.createParallelGroup(Alignment.TRAILING)
						.addComponent(lblPassword)
						.addComponent(usernameLabel))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addGroup(gl_contentPane.createParallelGroup(Alignment.LEADING)
						.addComponent(usernameField, GroupLayout.PREFERRED_SIZE, 235, GroupLayout.PREFERRED_SIZE)
						.addComponent(passwordField, GroupLayout.PREFERRED_SIZE, 235, GroupLayout.PREFERRED_SIZE))
					.addGap(53))
				.addGroup(gl_contentPane.createSequentialGroup()
					.addGap(60)
					.addComponent(lblLoginToYour)
					.addContainerGap(247, Short.MAX_VALUE))
				.addGroup(gl_contentPane.createSequentialGroup()
					.addGap(124)
					.addGroup(gl_contentPane.createParallelGroup(Alignment.TRAILING)
						.addComponent(btnBack, GroupLayout.PREFERRED_SIZE, 222, GroupLayout.PREFERRED_SIZE)
						.addComponent(btnLogin, GroupLayout.PREFERRED_SIZE, 223, GroupLayout.PREFERRED_SIZE))
					.addContainerGap(296, Short.MAX_VALUE))
		);
		gl_contentPane.setVerticalGroup(
			gl_contentPane.createParallelGroup(Alignment.TRAILING)
				.addGroup(gl_contentPane.createSequentialGroup()
					.addGap(50)
					.addComponent(lblLoginToYour)
					.addGap(52)
					.addGroup(gl_contentPane.createParallelGroup(Alignment.BASELINE)
						.addComponent(usernameField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(usernameLabel, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE))
					.addPreferredGap(ComponentPlacement.UNRELATED)
					.addGroup(gl_contentPane.createParallelGroup(Alignment.BASELINE)
						.addComponent(passwordField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(lblPassword, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE))
					.addGap(36)
					.addComponent(btnLogin, GroupLayout.PREFERRED_SIZE, 53, GroupLayout.PREFERRED_SIZE)
					.addGap(18)
					.addComponent(btnBack, GroupLayout.PREFERRED_SIZE, 56, GroupLayout.PREFERRED_SIZE)
					.addGap(44))
		);
		contentPane.setLayout(gl_contentPane);
	}

	@Override
	/**
	 * Will handle all the button actionlistener 
	 */
	public void actionPerformed(ActionEvent e)
	{
		if(e.getSource() == btnLogin)
		{
			this.dispose();
			System.out.println("Loggin in");
			// Send over the username and password to the server
			// receive a message from the server indicating whether to create new canvas or not
			try {
				//Get username and password
				String username = usernameField.getText();
				String password = passwordField.getText();
				client.loginRequest(username, password, this);
			} catch (Exception e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
		}
		else if(e.getSource() == btnBack)
		{
			
			this.dispose();
			System.out.println("Going back to main Screen");
			mainScreen.setVisible(true);

		}
	}

	public void successMessage()
	{
		JFrame diaFrame = new JFrame();
		JOptionPane.showMessageDialog(diaFrame,
				"Login successful.",
				"Success",
				JOptionPane.WARNING_MESSAGE);
	}

	public void failMessage()
	{
		JFrame diaFrame = new JFrame();
		JOptionPane.showMessageDialog(diaFrame,
				"Login failed. Incorrect credentials",
				"Error.",
				JOptionPane.WARNING_MESSAGE);
	}
}
